<?php
	/**
	 * TFN: 3ft9 Ltd PHP Component Library.
	 */
	namespace TFN;

	/**
	 * All exceptions generated by the TFN class library derive from this
	 * exception.
	 */
	class TFNException extends \Exception
	{
	}
